apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        lenoqt/jx3-k3s-vault: true
        lenoqt/pneumasoft-web-: true
        wilmerco/pneumasoft-web: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        lenoqt/jx3-k3s-vault: merge
        lenoqt/pneumasoft-web-: merge
        wilmerco/pneumasoft-web: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - lenoqt/jx3-k3s-vault
        - lenoqt/pneumasoft-web-
        - wilmerco/pneumasoft-web
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - lenoqt/jx3-k3s-vault
        - lenoqt/pneumasoft-web-
        - wilmerco/pneumasoft-web
      target_url: http://lighthouse.jx.192.168.0.9.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
